### ISSUE TITLE
Bab

### ISSUE THREAD

**Issue by Pr3mo333** [AxelConceicao/bustabit-script-simulator-2020#4]

**Comment by AxelConceicao** [comment]
?

**Comment by ghost** [comment]
Is this engine from current bustabit v2?

**Comment by AxelConceicao** [comment]
> Is this engine from current bustabit v2?

yeah its for Bustabit v2

**Comment by queenDev100** [comment]
I uploaded the updated version here:
https://github.com/queenDev100/Crash-Predictor-Roobet-Stake-Bustabit-Cloudbet .
